const data =  [
      {
          "cancelledElapsedTime": 0,
          "category": {
              "createdAt": "2023-05-25 12:29:53",
              "createdBy": 5,
              "deletedAt": null,
              "deletedBy": null,
              "etaEvent": null,
              "events": 0,
              "form": {
                  "id": 13,
                  "user_id": null,
                  "options": {
                      "urlTermsAndConditions": null,
                      "replyTo": "80",
                      "replyToName": "80",
                      "customLeadPDFTemplate": null
                  },
                  "parent_id": null,
                  "created_at": "2023-05-29T14:35:36.000000Z",
                  "updated_at": "2023-05-29T14:55:08.000000Z",
                  "system_name": "copias-factura-y-manifiesto",
                  "active": 1,
                  "destination_email": null,
                  "form_type": null,
                  "deleted_at": null,
                  "created_by": 1,
                  "updated_by": 5,
                  "deleted_by": null,
                  "organization_id": null,
                  "title": "Copias Factura Y Manifiesto",
                  "submit_text": null,
                  "success_text": null,
                  "description": null,
                  "pivot": {
                      "formeable_id": 8,
                      "form_id": 13,
                      "formeable_type": "Modules\\Requestable\\Entities\\Category",
                      "created_at": "2023-05-29T14:38:49.000000Z",
                      "updated_at": "2023-05-29T14:38:49.000000Z"
                  },
                  "translations": [
                      {
                          "id": 14,
                          "title": "Copias Factura Y Manifiesto",
                          "description": null,
                          "submit_text": null,
                          "success_text": null,
                          "form_id": 13,
                          "locale": "es"
                      }
                  ]
              },
              "formId": 13,
              "forms": [
                  {
                      "active": 1,
                      "createdAt": "2023-05-29 09:35:36",
                      "createdBy": 1,
                      "deletedAt": null,
                      "deletedBy": null,
                      "description": null,
                      "destinationEmail": null,
                      "embed": "<script id='scriptIframeId-696a587457aeb' src='https://dev-gestionhc.ozonohosting.com/iforms/external/render/13?iframeId=696a587457aeb'></script>",
                      "formType": null,
                      "id": 13,
                      "options": {
                          "urlTermsAndConditions": null,
                          "replyTo": "80",
                          "replyToName": "80",
                          "customLeadPDFTemplate": null
                      },
                      "organizationId": null,
                      "parentId": null,
                      "pivot": {
                          "createdAt": "2023-05-29 09:38:49",
                          "formId": 13,
                          "formeableId": 8,
                          "formeableType": "Modules\\Requestable\\Entities\\Category",
                          "updatedAt": "2023-05-29 09:38:49"
                      },
                      "submitText": null,
                      "successText": null,
                      "systemName": "copias-factura-y-manifiesto",
                      "title": "Copias Factura Y Manifiesto",
                      "updatedAt": "2023-05-29 09:55:08",
                      "updatedBy": 5,
                      "url": "https://dev-gestionhc.ozonohosting.com/iforms/view/13",
                      "userId": null
                  }
              ],
              "id": 8,
              "internal": 0,
              "options": null,
              "organizationId": null,
              "requestableType": null,
              "timeElapsedToCancel": 1,
              "title": "Copias Factura Y Manifiesto",
              "type": "copias-factura-y-manifiesto",
              "updatedAt": "2023-05-25 12:29:53",
              "updatedBy": 5
          },
          "categoryId": 8,
          "color": "#2ef2ec",
          "createdAt": "2023-05-29 08:57:11",
          "createdBy": 5,
          "default": 0,
          "deleteRequest": 0,
          "deletedAt": null,
          "deletedBy": null,
          "events": null,
          "final": 0,
          "id": 50,
          "organizationId": null,
          "position": 0,
          "title": "1.Solicitud copias de factura y manifiesto.",
          "type": 0,
          "typeName": "En Progreso",
          "updatedAt": "2026-01-15 17:16:25",
          "updatedBy": 1,
          "value": null
      },
      {
          "cancelledElapsedTime": 0,
          "category": {
              "createdAt": "2023-05-25 12:29:53",
              "createdBy": 5,
              "deletedAt": null,
              "deletedBy": null,
              "etaEvent": null,
              "events": 0,
              "form": {
                  "id": 13,
                  "user_id": null,
                  "options": {
                      "urlTermsAndConditions": null,
                      "replyTo": "80",
                      "replyToName": "80",
                      "customLeadPDFTemplate": null
                  },
                  "parent_id": null,
                  "created_at": "2023-05-29T14:35:36.000000Z",
                  "updated_at": "2023-05-29T14:55:08.000000Z",
                  "system_name": "copias-factura-y-manifiesto",
                  "active": 1,
                  "destination_email": null,
                  "form_type": null,
                  "deleted_at": null,
                  "created_by": 1,
                  "updated_by": 5,
                  "deleted_by": null,
                  "organization_id": null,
                  "title": "Copias Factura Y Manifiesto",
                  "submit_text": null,
                  "success_text": null,
                  "description": null,
                  "pivot": {
                      "formeable_id": 8,
                      "form_id": 13,
                      "formeable_type": "Modules\\Requestable\\Entities\\Category",
                      "created_at": "2023-05-29T14:38:49.000000Z",
                      "updated_at": "2023-05-29T14:38:49.000000Z"
                  },
                  "translations": [
                      {
                          "id": 14,
                          "title": "Copias Factura Y Manifiesto",
                          "description": null,
                          "submit_text": null,
                          "success_text": null,
                          "form_id": 13,
                          "locale": "es"
                      }
                  ]
              },
              "formId": 13,
              "forms": [
                  {
                      "active": 1,
                      "createdAt": "2023-05-29 09:35:36",
                      "createdBy": 1,
                      "deletedAt": null,
                      "deletedBy": null,
                      "description": null,
                      "destinationEmail": null,
                      "embed": "<script id='scriptIframeId-696a587458f93' src='https://dev-gestionhc.ozonohosting.com/iforms/external/render/13?iframeId=696a587458f93'></script>",
                      "formType": null,
                      "id": 13,
                      "options": {
                          "urlTermsAndConditions": null,
                          "replyTo": "80",
                          "replyToName": "80",
                          "customLeadPDFTemplate": null
                      },
                      "organizationId": null,
                      "parentId": null,
                      "pivot": {
                          "createdAt": "2023-05-29 09:38:49",
                          "formId": 13,
                          "formeableId": 8,
                          "formeableType": "Modules\\Requestable\\Entities\\Category",
                          "updatedAt": "2023-05-29 09:38:49"
                      },
                      "submitText": null,
                      "successText": null,
                      "systemName": "copias-factura-y-manifiesto",
                      "title": "Copias Factura Y Manifiesto",
                      "updatedAt": "2023-05-29 09:55:08",
                      "updatedBy": 5,
                      "url": "https://dev-gestionhc.ozonohosting.com/iforms/view/13",
                      "userId": null
                  }
              ],
              "id": 8,
              "internal": 0,
              "options": null,
              "organizationId": null,
              "requestableType": null,
              "timeElapsedToCancel": 1,
              "title": "Copias Factura Y Manifiesto",
              "type": "copias-factura-y-manifiesto",
              "updatedAt": "2023-05-25 12:29:53",
              "updatedBy": 5
          },
          "categoryId": 8,
          "color": "#ff03d9",
          "createdAt": "2023-05-29 08:58:09",
          "createdBy": 5,
          "default": 0,
          "deleteRequest": 0,
          "deletedAt": null,
          "deletedBy": null,
          "events": null,
          "final": 0,
          "id": 51,
          "organizationId": null,
          "position": 1,
          "title": "Contactado",
          "type": 0,
          "typeName": "En Progreso",
          "updatedAt": "2026-01-14 13:00:11",
          "updatedBy": 1,
          "value": null
      },
      {
          "cancelledElapsedTime": 0,
          "category": {
              "createdAt": "2023-05-25 12:29:53",
              "createdBy": 5,
              "deletedAt": null,
              "deletedBy": null,
              "etaEvent": null,
              "events": 0,
              "form": {
                  "id": 13,
                  "user_id": null,
                  "options": {
                      "urlTermsAndConditions": null,
                      "replyTo": "80",
                      "replyToName": "80",
                      "customLeadPDFTemplate": null
                  },
                  "parent_id": null,
                  "created_at": "2023-05-29T14:35:36.000000Z",
                  "updated_at": "2023-05-29T14:55:08.000000Z",
                  "system_name": "copias-factura-y-manifiesto",
                  "active": 1,
                  "destination_email": null,
                  "form_type": null,
                  "deleted_at": null,
                  "created_by": 1,
                  "updated_by": 5,
                  "deleted_by": null,
                  "organization_id": null,
                  "title": "Copias Factura Y Manifiesto",
                  "submit_text": null,
                  "success_text": null,
                  "description": null,
                  "pivot": {
                      "formeable_id": 8,
                      "form_id": 13,
                      "formeable_type": "Modules\\Requestable\\Entities\\Category",
                      "created_at": "2023-05-29T14:38:49.000000Z",
                      "updated_at": "2023-05-29T14:38:49.000000Z"
                  },
                  "translations": [
                      {
                          "id": 14,
                          "title": "Copias Factura Y Manifiesto",
                          "description": null,
                          "submit_text": null,
                          "success_text": null,
                          "form_id": 13,
                          "locale": "es"
                      }
                  ]
              },
              "formId": 13,
              "forms": [
                  {
                      "active": 1,
                      "createdAt": "2023-05-29 09:35:36",
                      "createdBy": 1,
                      "deletedAt": null,
                      "deletedBy": null,
                      "description": null,
                      "destinationEmail": null,
                      "embed": "<script id='scriptIframeId-696a58745a3e8' src='https://dev-gestionhc.ozonohosting.com/iforms/external/render/13?iframeId=696a58745a3e8'></script>",
                      "formType": null,
                      "id": 13,
                      "options": {
                          "urlTermsAndConditions": null,
                          "replyTo": "80",
                          "replyToName": "80",
                          "customLeadPDFTemplate": null
                      },
                      "organizationId": null,
                      "parentId": null,
                      "pivot": {
                          "createdAt": "2023-05-29 09:38:49",
                          "formId": 13,
                          "formeableId": 8,
                          "formeableType": "Modules\\Requestable\\Entities\\Category",
                          "updatedAt": "2023-05-29 09:38:49"
                      },
                      "submitText": null,
                      "successText": null,
                      "systemName": "copias-factura-y-manifiesto",
                      "title": "Copias Factura Y Manifiesto",
                      "updatedAt": "2023-05-29 09:55:08",
                      "updatedBy": 5,
                      "url": "https://dev-gestionhc.ozonohosting.com/iforms/view/13",
                      "userId": null
                  }
              ],
              "id": 8,
              "internal": 0,
              "options": null,
              "organizationId": null,
              "requestableType": null,
              "timeElapsedToCancel": 1,
              "title": "Copias Factura Y Manifiesto",
              "type": "copias-factura-y-manifiesto",
              "updatedAt": "2023-05-25 12:29:53",
              "updatedBy": 5
          },
          "categoryId": 8,
          "color": "#ac806e",
          "createdAt": "2024-02-16 15:04:58",
          "createdBy": 1,
          "default": 0,
          "deleteRequest": 0,
          "deletedAt": null,
          "deletedBy": null,
          "events": null,
          "final": 0,
          "id": 56,
          "organizationId": null,
          "position": 2,
          "title": "Nuevo",
          "type": 0,
          "typeName": "En Progreso",
          "updatedAt": "2026-01-15 17:16:25",
          "updatedBy": 1,
          "value": null
      },
      {
          "cancelledElapsedTime": 0,
          "category": {
              "createdAt": "2023-05-25 12:29:53",
              "createdBy": 5,
              "deletedAt": null,
              "deletedBy": null,
              "etaEvent": null,
              "events": 0,
              "form": {
                  "id": 13,
                  "user_id": null,
                  "options": {
                      "urlTermsAndConditions": null,
                      "replyTo": "80",
                      "replyToName": "80",
                      "customLeadPDFTemplate": null
                  },
                  "parent_id": null,
                  "created_at": "2023-05-29T14:35:36.000000Z",
                  "updated_at": "2023-05-29T14:55:08.000000Z",
                  "system_name": "copias-factura-y-manifiesto",
                  "active": 1,
                  "destination_email": null,
                  "form_type": null,
                  "deleted_at": null,
                  "created_by": 1,
                  "updated_by": 5,
                  "deleted_by": null,
                  "organization_id": null,
                  "title": "Copias Factura Y Manifiesto",
                  "submit_text": null,
                  "success_text": null,
                  "description": null,
                  "pivot": {
                      "formeable_id": 8,
                      "form_id": 13,
                      "formeable_type": "Modules\\Requestable\\Entities\\Category",
                      "created_at": "2023-05-29T14:38:49.000000Z",
                      "updated_at": "2023-05-29T14:38:49.000000Z"
                  },
                  "translations": [
                      {
                          "id": 14,
                          "title": "Copias Factura Y Manifiesto",
                          "description": null,
                          "submit_text": null,
                          "success_text": null,
                          "form_id": 13,
                          "locale": "es"
                      }
                  ]
              },
              "formId": 13,
              "forms": [
                  {
                      "active": 1,
                      "createdAt": "2023-05-29 09:35:36",
                      "createdBy": 1,
                      "deletedAt": null,
                      "deletedBy": null,
                      "description": null,
                      "destinationEmail": null,
                      "embed": "<script id='scriptIframeId-696a58745b831' src='https://dev-gestionhc.ozonohosting.com/iforms/external/render/13?iframeId=696a58745b831'></script>",
                      "formType": null,
                      "id": 13,
                      "options": {
                          "urlTermsAndConditions": null,
                          "replyTo": "80",
                          "replyToName": "80",
                          "customLeadPDFTemplate": null
                      },
                      "organizationId": null,
                      "parentId": null,
                      "pivot": {
                          "createdAt": "2023-05-29 09:38:49",
                          "formId": 13,
                          "formeableId": 8,
                          "formeableType": "Modules\\Requestable\\Entities\\Category",
                          "updatedAt": "2023-05-29 09:38:49"
                      },
                      "submitText": null,
                      "successText": null,
                      "systemName": "copias-factura-y-manifiesto",
                      "title": "Copias Factura Y Manifiesto",
                      "updatedAt": "2023-05-29 09:55:08",
                      "updatedBy": 5,
                      "url": "https://dev-gestionhc.ozonohosting.com/iforms/view/13",
                      "userId": null
                  }
              ],
              "id": 8,
              "internal": 0,
              "options": null,
              "organizationId": null,
              "requestableType": null,
              "timeElapsedToCancel": 1,
              "title": "Copias Factura Y Manifiesto",
              "type": "copias-factura-y-manifiesto",
              "updatedAt": "2023-05-25 12:29:53",
              "updatedBy": 5
          },
          "categoryId": 8,
          "color": "#2b2222",
          "createdAt": "2024-02-19 09:15:03",
          "createdBy": 1,
          "default": 0,
          "deleteRequest": 0,
          "deletedAt": null,
          "deletedBy": null,
          "events": null,
          "final": 0,
          "id": 57,
          "organizationId": null,
          "position": 3,
          "title": "hanna",
          "type": 1,
          "typeName": "Fallido",
          "updatedAt": "2025-11-14 17:54:09",
          "updatedBy": 1,
          "value": null
      },
      {
          "cancelledElapsedTime": 0,
          "category": {
              "createdAt": "2023-05-25 12:29:53",
              "createdBy": 5,
              "deletedAt": null,
              "deletedBy": null,
              "etaEvent": null,
              "events": 0,
              "form": {
                  "id": 13,
                  "user_id": null,
                  "options": {
                      "urlTermsAndConditions": null,
                      "replyTo": "80",
                      "replyToName": "80",
                      "customLeadPDFTemplate": null
                  },
                  "parent_id": null,
                  "created_at": "2023-05-29T14:35:36.000000Z",
                  "updated_at": "2023-05-29T14:55:08.000000Z",
                  "system_name": "copias-factura-y-manifiesto",
                  "active": 1,
                  "destination_email": null,
                  "form_type": null,
                  "deleted_at": null,
                  "created_by": 1,
                  "updated_by": 5,
                  "deleted_by": null,
                  "organization_id": null,
                  "title": "Copias Factura Y Manifiesto",
                  "submit_text": null,
                  "success_text": null,
                  "description": null,
                  "pivot": {
                      "formeable_id": 8,
                      "form_id": 13,
                      "formeable_type": "Modules\\Requestable\\Entities\\Category",
                      "created_at": "2023-05-29T14:38:49.000000Z",
                      "updated_at": "2023-05-29T14:38:49.000000Z"
                  },
                  "translations": [
                      {
                          "id": 14,
                          "title": "Copias Factura Y Manifiesto",
                          "description": null,
                          "submit_text": null,
                          "success_text": null,
                          "form_id": 13,
                          "locale": "es"
                      }
                  ]
              },
              "formId": 13,
              "forms": [
                  {
                      "active": 1,
                      "createdAt": "2023-05-29 09:35:36",
                      "createdBy": 1,
                      "deletedAt": null,
                      "deletedBy": null,
                      "description": null,
                      "destinationEmail": null,
                      "embed": "<script id='scriptIframeId-696a58745cc7b' src='https://dev-gestionhc.ozonohosting.com/iforms/external/render/13?iframeId=696a58745cc7b'></script>",
                      "formType": null,
                      "id": 13,
                      "options": {
                          "urlTermsAndConditions": null,
                          "replyTo": "80",
                          "replyToName": "80",
                          "customLeadPDFTemplate": null
                      },
                      "organizationId": null,
                      "parentId": null,
                      "pivot": {
                          "createdAt": "2023-05-29 09:38:49",
                          "formId": 13,
                          "formeableId": 8,
                          "formeableType": "Modules\\Requestable\\Entities\\Category",
                          "updatedAt": "2023-05-29 09:38:49"
                      },
                      "submitText": null,
                      "successText": null,
                      "systemName": "copias-factura-y-manifiesto",
                      "title": "Copias Factura Y Manifiesto",
                      "updatedAt": "2023-05-29 09:55:08",
                      "updatedBy": 5,
                      "url": "https://dev-gestionhc.ozonohosting.com/iforms/view/13",
                      "userId": null
                  }
              ],
              "id": 8,
              "internal": 0,
              "options": null,
              "organizationId": null,
              "requestableType": null,
              "timeElapsedToCancel": 1,
              "title": "Copias Factura Y Manifiesto",
              "type": "copias-factura-y-manifiesto",
              "updatedAt": "2023-05-25 12:29:53",
              "updatedBy": 5
          },
          "categoryId": 8,
          "color": "#241d19",
          "createdAt": "2024-02-19 09:15:23",
          "createdBy": 1,
          "default": 0,
          "deleteRequest": 0,
          "deletedAt": null,
          "deletedBy": null,
          "events": null,
          "final": 0,
          "id": 58,
          "organizationId": null,
          "position": 4,
          "title": "jose",
          "type": 1,
          "typeName": "Fallido",
          "updatedAt": "2025-11-14 17:54:09",
          "updatedBy": 1,
          "value": null
      },
      {
          "cancelledElapsedTime": 0,
          "category": {
              "createdAt": "2023-05-25 12:29:53",
              "createdBy": 5,
              "deletedAt": null,
              "deletedBy": null,
              "etaEvent": null,
              "events": 0,
              "form": {
                  "id": 13,
                  "user_id": null,
                  "options": {
                      "urlTermsAndConditions": null,
                      "replyTo": "80",
                      "replyToName": "80",
                      "customLeadPDFTemplate": null
                  },
                  "parent_id": null,
                  "created_at": "2023-05-29T14:35:36.000000Z",
                  "updated_at": "2023-05-29T14:55:08.000000Z",
                  "system_name": "copias-factura-y-manifiesto",
                  "active": 1,
                  "destination_email": null,
                  "form_type": null,
                  "deleted_at": null,
                  "created_by": 1,
                  "updated_by": 5,
                  "deleted_by": null,
                  "organization_id": null,
                  "title": "Copias Factura Y Manifiesto",
                  "submit_text": null,
                  "success_text": null,
                  "description": null,
                  "pivot": {
                      "formeable_id": 8,
                      "form_id": 13,
                      "formeable_type": "Modules\\Requestable\\Entities\\Category",
                      "created_at": "2023-05-29T14:38:49.000000Z",
                      "updated_at": "2023-05-29T14:38:49.000000Z"
                  },
                  "translations": [
                      {
                          "id": 14,
                          "title": "Copias Factura Y Manifiesto",
                          "description": null,
                          "submit_text": null,
                          "success_text": null,
                          "form_id": 13,
                          "locale": "es"
                      }
                  ]
              },
              "formId": 13,
              "forms": [
                  {
                      "active": 1,
                      "createdAt": "2023-05-29 09:35:36",
                      "createdBy": 1,
                      "deletedAt": null,
                      "deletedBy": null,
                      "description": null,
                      "destinationEmail": null,
                      "embed": "<script id='scriptIframeId-696a58745e0c9' src='https://dev-gestionhc.ozonohosting.com/iforms/external/render/13?iframeId=696a58745e0c9'></script>",
                      "formType": null,
                      "id": 13,
                      "options": {
                          "urlTermsAndConditions": null,
                          "replyTo": "80",
                          "replyToName": "80",
                          "customLeadPDFTemplate": null
                      },
                      "organizationId": null,
                      "parentId": null,
                      "pivot": {
                          "createdAt": "2023-05-29 09:38:49",
                          "formId": 13,
                          "formeableId": 8,
                          "formeableType": "Modules\\Requestable\\Entities\\Category",
                          "updatedAt": "2023-05-29 09:38:49"
                      },
                      "submitText": null,
                      "successText": null,
                      "systemName": "copias-factura-y-manifiesto",
                      "title": "Copias Factura Y Manifiesto",
                      "updatedAt": "2023-05-29 09:55:08",
                      "updatedBy": 5,
                      "url": "https://dev-gestionhc.ozonohosting.com/iforms/view/13",
                      "userId": null
                  }
              ],
              "id": 8,
              "internal": 0,
              "options": null,
              "organizationId": null,
              "requestableType": null,
              "timeElapsedToCancel": 1,
              "title": "Copias Factura Y Manifiesto",
              "type": "copias-factura-y-manifiesto",
              "updatedAt": "2023-05-25 12:29:53",
              "updatedBy": 5
          },
          "categoryId": 8,
          "color": "#d41c1c",
          "createdAt": "2024-02-19 09:15:44",
          "createdBy": 1,
          "default": 0,
          "deleteRequest": 0,
          "deletedAt": null,
          "deletedBy": null,
          "events": null,
          "final": 0,
          "id": 59,
          "organizationId": null,
          "position": 5,
          "title": "wilmer",
          "type": 1,
          "typeName": "Fallido",
          "updatedAt": "2026-01-15 17:16:25",
          "updatedBy": 1,
          "value": null
      },
      {
          "cancelledElapsedTime": 0,
          "category": {
              "createdAt": "2023-05-25 12:29:53",
              "createdBy": 5,
              "deletedAt": null,
              "deletedBy": null,
              "etaEvent": null,
              "events": 0,
              "form": {
                  "id": 13,
                  "user_id": null,
                  "options": {
                      "urlTermsAndConditions": null,
                      "replyTo": "80",
                      "replyToName": "80",
                      "customLeadPDFTemplate": null
                  },
                  "parent_id": null,
                  "created_at": "2023-05-29T14:35:36.000000Z",
                  "updated_at": "2023-05-29T14:55:08.000000Z",
                  "system_name": "copias-factura-y-manifiesto",
                  "active": 1,
                  "destination_email": null,
                  "form_type": null,
                  "deleted_at": null,
                  "created_by": 1,
                  "updated_by": 5,
                  "deleted_by": null,
                  "organization_id": null,
                  "title": "Copias Factura Y Manifiesto",
                  "submit_text": null,
                  "success_text": null,
                  "description": null,
                  "pivot": {
                      "formeable_id": 8,
                      "form_id": 13,
                      "formeable_type": "Modules\\Requestable\\Entities\\Category",
                      "created_at": "2023-05-29T14:38:49.000000Z",
                      "updated_at": "2023-05-29T14:38:49.000000Z"
                  },
                  "translations": [
                      {
                          "id": 14,
                          "title": "Copias Factura Y Manifiesto",
                          "description": null,
                          "submit_text": null,
                          "success_text": null,
                          "form_id": 13,
                          "locale": "es"
                      }
                  ]
              },
              "formId": 13,
              "forms": [
                  {
                      "active": 1,
                      "createdAt": "2023-05-29 09:35:36",
                      "createdBy": 1,
                      "deletedAt": null,
                      "deletedBy": null,
                      "description": null,
                      "destinationEmail": null,
                      "embed": "<script id='scriptIframeId-696a58745f4f8' src='https://dev-gestionhc.ozonohosting.com/iforms/external/render/13?iframeId=696a58745f4f8'></script>",
                      "formType": null,
                      "id": 13,
                      "options": {
                          "urlTermsAndConditions": null,
                          "replyTo": "80",
                          "replyToName": "80",
                          "customLeadPDFTemplate": null
                      },
                      "organizationId": null,
                      "parentId": null,
                      "pivot": {
                          "createdAt": "2023-05-29 09:38:49",
                          "formId": 13,
                          "formeableId": 8,
                          "formeableType": "Modules\\Requestable\\Entities\\Category",
                          "updatedAt": "2023-05-29 09:38:49"
                      },
                      "submitText": null,
                      "successText": null,
                      "systemName": "copias-factura-y-manifiesto",
                      "title": "Copias Factura Y Manifiesto",
                      "updatedAt": "2023-05-29 09:55:08",
                      "updatedBy": 5,
                      "url": "https://dev-gestionhc.ozonohosting.com/iforms/view/13",
                      "userId": null
                  }
              ],
              "id": 8,
              "internal": 0,
              "options": null,
              "organizationId": null,
              "requestableType": null,
              "timeElapsedToCancel": 1,
              "title": "Copias Factura Y Manifiesto",
              "type": "copias-factura-y-manifiesto",
              "updatedAt": "2023-05-25 12:29:53",
              "updatedBy": 5
          },
          "categoryId": 8,
          "color": "#666e0",
          "createdAt": "2025-12-19 11:43:44",
          "createdBy": 1,
          "default": 0,
          "deleteRequest": 0,
          "deletedAt": null,
          "deletedBy": null,
          "events": null,
          "final": 0,
          "id": 70,
          "organizationId": null,
          "position": 6,
          "title": "hello",
          "type": 1,
          "typeName": "Fallido",
          "updatedAt": "2026-01-15 17:16:25",
          "updatedBy": 1,
          "value": null
      },
      {
          "cancelledElapsedTime": 0,
          "category": {
              "createdAt": "2023-05-25 12:29:53",
              "createdBy": 5,
              "deletedAt": null,
              "deletedBy": null,
              "etaEvent": null,
              "events": 0,
              "form": {
                  "id": 13,
                  "user_id": null,
                  "options": {
                      "urlTermsAndConditions": null,
                      "replyTo": "80",
                      "replyToName": "80",
                      "customLeadPDFTemplate": null
                  },
                  "parent_id": null,
                  "created_at": "2023-05-29T14:35:36.000000Z",
                  "updated_at": "2023-05-29T14:55:08.000000Z",
                  "system_name": "copias-factura-y-manifiesto",
                  "active": 1,
                  "destination_email": null,
                  "form_type": null,
                  "deleted_at": null,
                  "created_by": 1,
                  "updated_by": 5,
                  "deleted_by": null,
                  "organization_id": null,
                  "title": "Copias Factura Y Manifiesto",
                  "submit_text": null,
                  "success_text": null,
                  "description": null,
                  "pivot": {
                      "formeable_id": 8,
                      "form_id": 13,
                      "formeable_type": "Modules\\Requestable\\Entities\\Category",
                      "created_at": "2023-05-29T14:38:49.000000Z",
                      "updated_at": "2023-05-29T14:38:49.000000Z"
                  },
                  "translations": [
                      {
                          "id": 14,
                          "title": "Copias Factura Y Manifiesto",
                          "description": null,
                          "submit_text": null,
                          "success_text": null,
                          "form_id": 13,
                          "locale": "es"
                      }
                  ]
              },
              "formId": 13,
              "forms": [
                  {
                      "active": 1,
                      "createdAt": "2023-05-29 09:35:36",
                      "createdBy": 1,
                      "deletedAt": null,
                      "deletedBy": null,
                      "description": null,
                      "destinationEmail": null,
                      "embed": "<script id='scriptIframeId-696a58746092d' src='https://dev-gestionhc.ozonohosting.com/iforms/external/render/13?iframeId=696a58746092d'></script>",
                      "formType": null,
                      "id": 13,
                      "options": {
                          "urlTermsAndConditions": null,
                          "replyTo": "80",
                          "replyToName": "80",
                          "customLeadPDFTemplate": null
                      },
                      "organizationId": null,
                      "parentId": null,
                      "pivot": {
                          "createdAt": "2023-05-29 09:38:49",
                          "formId": 13,
                          "formeableId": 8,
                          "formeableType": "Modules\\Requestable\\Entities\\Category",
                          "updatedAt": "2023-05-29 09:38:49"
                      },
                      "submitText": null,
                      "successText": null,
                      "systemName": "copias-factura-y-manifiesto",
                      "title": "Copias Factura Y Manifiesto",
                      "updatedAt": "2023-05-29 09:55:08",
                      "updatedBy": 5,
                      "url": "https://dev-gestionhc.ozonohosting.com/iforms/view/13",
                      "userId": null
                  }
              ],
              "id": 8,
              "internal": 0,
              "options": null,
              "organizationId": null,
              "requestableType": null,
              "timeElapsedToCancel": 1,
              "title": "Copias Factura Y Manifiesto",
              "type": "copias-factura-y-manifiesto",
              "updatedAt": "2023-05-25 12:29:53",
              "updatedBy": 5
          },
          "categoryId": 8,
          "color": "#96d9d5",
          "createdAt": "2025-12-19 11:44:07",
          "createdBy": 1,
          "default": 0,
          "deleteRequest": 0,
          "deletedAt": null,
          "deletedBy": null,
          "events": null,
          "final": 0,
          "id": 71,
          "organizationId": null,
          "position": 7,
          "title": "testt",
          "type": 1,
          "typeName": "Fallido",
          "updatedAt": "2026-01-15 17:16:25",
          "updatedBy": 1,
          "value": null
      }
  ]

  const meta = {
        "page": {
            "total": 1,
            "lastPage": 1,
            "perPage": "10",
            "currentPage": 1
        }
    }

function list(){
    return {data, meta}
}

export default {
    list
}
